# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 379ac2ab30a6c186d0b70cb36f2e14496c5bfef27b6f1afba83083e06a1418b269cf79a57140efd693aed7d2fa461c069d69845ec0741af857e3d1708f5c2a26

test:
  secret_key_base: 51dc26aa2a892864d31414edb044a3697382f742f708fb800cfd8bdf884a2cf28c3bb2c30c7d209877cb9f9040c0cbcd92ad3e528c86facc9da5d9769a8a2dd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
